---
- name:           Remove old versions
  yum:
    name:         "{{ item }}"
    state:        absent
  with_items:     "{{ docker_old_packages }}"

- name:           Add Docker Repo
  yum_repository:
    name:         docker-ce-stable
    description:  "Docker CE Stable - $basearch"
    baseurl:      "https://download.docker.com/linux/centos/7/$basearch/stable"
    enabled:      yes
    gpgcheck:     yes
    gpgkey:       https://download.docker.com/linux/centos/gpg

- name:           Install Docker Engine
  yum:
    name:         "docker-ce-{{ docker_version }}"
    state:        present

- name:           Start Docker Service
  service:
    name:         docker
    state:        started
    enabled:      yes

- name:           Add vagrant user to docker group.
  user:
    name:         vagrant
    groups:       docker
    append:       yes
  become:         yes
